Fix an error when running `rake rubocop:auto_correct`
This PR fixes the following error when running deprecated `rake rubocop:auto_correct` task:

```console
$ cat Rakefile
require 'rubocop/rake_task'
RuboCop::RakeTask.new { |task| task.patterns = ['lib/'] }

$ rake rubocop:auto_correct
rubocop:auto_correct task is deprecated; use rubocop:autocorrect task or rubocop:autocorrect_all task instead.
rake aborted!
NameError: undefined local variable or method 'task_args' for an instance of RuboCop::RakeTask (NameError)

            yield(*[self, task_args].slice(0, task_block.arity)) if task_block
                          ^^^^^^^^^
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/rake_task.rb:85:in 'block (3 levels) in RuboCop::RakeTask#setup_subtasks'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/rake_task.rb:84:in 'block (2 levels) in RuboCop::RakeTask#setup_subtasks'
/Users/koic/.rbenv/versions/3.5-dev/bin/bundle:25:in '<main>'
Tasks: TOP => rubocop:auto_correct
(See full trace by running task with --trace)
```